replicaCount: 2

image:
  repository: ""
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: []

serviceAccount:
  create: false
  name: ""
  automount: false

ingress:
  enabled: false
