replicaCount: 2

image:
  repository: 478517495773.dkr.ecr.us-east-1.amazonaws.com/flask-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 5000

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: []

serviceAccount:
  create: false
  name: ""
  automount: false

ingress:
  enabled: false
